### PR TITLE
Change name values sa_AR

### PR DESCRIPTION
**Pull request by mahkassem**
This will change foodNames and meatNames to match Arabic region names

### CODE REVIEW

**Comment by jzonta** [comment]
Why did you remove pork meat?
You made unnecessary changes to README.md

**Comment by jzonta** [comment]
PR Closed

**Comment by mahkassem** [comment]
Respect your hard work, sorry for the late response; I was very busy lately,
Pork meat is not used in Arabic speaking countries, so a lot of customers don't find it relevant for demonstration.

**Comment by jzonta** [comment]
> Respect your hard work, sorry for the late response; I was very busy lately, Pork meat is not used in Arabic speaking countries, so a lot of customers don't find it relevant for demonstration.

In this case, I'm reopening PR, but you need to remove your updates in readme.md, because it's not necessary. I appreciate your work and wait for a new commit removing the changes in the readme.

**Review by mahkassem — COMMENTED** [review]
I think I deleted file as update instead of removing the changes only!, I will fix this and commit again, sorry!

**Review by mahkassem — COMMENTED** [review]
add Original README.md file

**Comment by jzonta** [comment]
I added your update through Cherry Pic, because you updated 2 PR files, it's not necessary. I mentioned you in [Release v2.0.1](https://github.com/jzonta/FakerRestaurant/releases/tag/v2.0.1)

Thanks for your contribution

**Pull request closed without merging**
